[project]
name = "bitcoin-bazaar"
authors = ["Vaios0x"]
description = "The first Bitcoin-native NFT marketplace"
telemetry = false
cache_dir = ".cache"

[contracts.nft-core]
path = "contracts/nft-core-simple.clar"

[contracts.marketplace-core]
path = "contracts/marketplace-core-simple.clar"

[contracts.bitcoin-oracle]
path = "contracts/bitcoin-oracle-simple.clar"

[contracts.gaming-nft]
path = "contracts/gaming-nft-simple.clar"

[contracts.nft-defi]
path = "contracts/nft-defi-simple.clar"

[contracts.lazy-mint]
path = "contracts/lazy-mint-simple.clar"

[contracts.analytics]
path = "contracts/analytics-simple.clar"

[contracts.governance]
path = "contracts/governance-simple.clar"

[contracts.escrow]
path = "contracts/escrow-simple-fixed.clar"

[contracts.rewards]
path = "contracts/rewards-simple.clar"