[project]
name = 'bitcoin-bazaar'
description = 'The first Bitcoin-native NFT marketplace'
authors = ['Vaios0x']
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'
[contracts.analytics]
path = 'contracts/analytics.clar'
clarity_version = 3
epoch = 'latest'

[contracts.analytics-sbtc-real]
path = 'contracts/analytics-sbtc-real.clar'
clarity_version = 3
epoch = 'latest'

[contracts.simple-sbtc-marketplace]
path = 'contracts/simple-sbtc-marketplace.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sbtc-token-mock]
path = 'contracts/sbtc-token-mock.clar'
clarity_version = 3
epoch = 'latest'

[contracts.bitcoin-oracle]
path = 'contracts/bitcoin-oracle.clar'
clarity_version = 3
epoch = 'latest'

[contracts.gaming-nft]
path = 'contracts/gaming-nft.clar'
clarity_version = 3
epoch = 'latest'

[contracts.gaming-nft-simple]
path = 'contracts/gaming-nft-simple.clar'
clarity_version = 3
epoch = 'latest'

[contracts.gaming-nft-sbtc-real]
path = 'contracts/gaming-nft-sbtc-real.clar'
clarity_version = 3
epoch = 'latest'

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = 'latest'

[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 3
epoch = 'latest'

[contracts.marketplace-sbtc-real]
path = 'contracts/marketplace-sbtc-real.clar'
clarity_version = 3
epoch = 'latest'

[contracts.nft-core]
path = 'contracts/nft-core.clar'
clarity_version = 3
epoch = 'latest'

[contracts.nft-defi]
path = 'contracts/nft-defi.clar'
clarity_version = 3
epoch = 'latest'

[contracts.nft-defi-sbtc-real]
path = 'contracts/nft-defi-sbtc-real.clar'
clarity_version = 3
epoch = 'latest'

[contracts.rewards]
path = 'contracts/rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sbtc-mock]
path = 'contracts/sbtc-mock.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
