import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bitcoin: {
          50: '#FFF7ED',
          100: '#FFEDD5',
          200: '#FED7AA',
          300: '#FDBA74',
          400: '#FB923C',
          500: '#F97316',
          600: '#EA580C',
          700: '#C2410C',
          800: '#9A3412',
          900: '#7C2D12',
        },
        stacks: {
          50: '#F0F9FF',
          100: '#E0F2FE',
          200: '#BAE6FD',
          300: '#7DD3FC',
          400: '#38BDF8',
          500: '#5546FF',
          600: '#4338CA',
          700: '#3730A3',
          800: '#312E81',
          900: '#1E1B4B',
        },
        sbtc: {
          50: '#FEF3C7',
          100: '#FDE68A',
          200: '#FCD34D',
          300: '#FBBF24',
          400: '#F59E0B',
          500: '#D97706',
          600: '#B45309',
          700: '#92400E',
          800: '#78350F',
          900: '#451A03',
        },
        neural: {
          background: '#0A0E27',
          surface: 'rgba(15, 23, 42, 0.6)',
          glass: 'rgba(255, 255, 255, 0.05)',
          premium: 'rgba(255, 255, 255, 0.12)',
        },
        glass: {
          bitcoin: 'rgba(249, 115, 22, 0.08)',
          stacks: 'rgba(85, 70, 255, 0.08)',
          premium: 'rgba(255, 255, 255, 0.12)',
          default: 'rgba(255, 255, 255, 0.08)',
        },
        // Advanced Holographic Colors
        holographic: {
          primary: '#06B6D4',
          secondary: '#8B5CF6',
          accent: '#F59E0B',
          glow: '#10B981',
        },
        // Premium Status Colors
        success: {
          50: '#ECFDF5',
          100: '#D1FAE5',
          200: '#A7F3D0',
          300: '#6EE7B7',
          400: '#34D399',
          500: '#10B981',
          600: '#059669',
          700: '#047857',
          800: '#065F46',
          900: '#064E3B',
        },
        warning: {
          50: '#FFFBEB',
          100: '#FEF3C7',
          200: '#FDE68A',
          300: '#FCD34D',
          400: '#FBBF24',
          500: '#F59E0B',
          600: '#D97706',
          700: '#B45309',
          800: '#92400E',
          900: '#78350F',
        },
        error: {
          50: '#FEF2F2',
          100: '#FEE2E2',
          200: '#FECACA',
          300: '#FCA5A5',
          400: '#F87171',
          500: '#EF4444',
          600: '#DC2626',
          700: '#B91C1C',
          800: '#991B1B',
          900: '#7F1D1D',
        },
        info: {
          50: '#EFF6FF',
          100: '#DBEAFE',
          200: '#BFDBFE',
          300: '#93C5FD',
          400: '#60A5FA',
          500: '#3B82F6',
          600: '#2563EB',
          700: '#1D4ED8',
          800: '#1E40AF',
          900: '#1E3A8A',
        },
      },
      animation: {
        'neural-pulse': 'neural-pulse 25s ease-in-out infinite',
        'neural-drift': 'neural-drift 40s linear infinite',
        'neural-aurora': 'neural-aurora 30s ease-in-out infinite',
        'neon-flicker': 'neon-flicker 4s ease-in-out infinite',
        'neon-pulse': 'neon-pulse 2s ease-in-out infinite',
        'bitcoin-pulse': 'bitcoin-pulse 3s ease-in-out infinite',
        'stacks-pulse': 'stacks-pulse 2.5s ease-in-out infinite',
        'holographic-shift': 'holographic-shift 6s ease-in-out infinite',
        'particles-float': 'particles-float 20s linear infinite',
        'gradient-shift': 'gradient-shift 4s ease-in-out infinite',
        'bitcoin-gradient': 'bitcoin-gradient 3s ease-in-out infinite',
        'stacks-gradient': 'stacks-gradient 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'float-enhanced': 'float 8s ease-in-out infinite',
        'pulse-enhanced': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        // Premium Animations
        'holographic-glow': 'holographic-glow 4s ease-in-out infinite',
        'cyber-scan': 'cyber-scan 3s linear infinite',
        'bitcoin-mining': 'bitcoin-mining 2s ease-in-out infinite',
        'neural-connection': 'neural-connection 5s ease-in-out infinite',
        'particle-burst': 'particle-burst 0.6s ease-out',
        'energy-flow': 'energy-flow 2s ease-in-out infinite',
        'blockchain-pulse': 'blockchain-pulse 4s ease-in-out infinite',
        'holographic-rainbow': 'holographic-rainbow 8s linear infinite',
        'cyber-grid': 'cyber-grid 20s linear infinite',
        'bitcoin-symbol-float': 'bitcoin-symbol-float 6s ease-in-out infinite',
        'stacks-network': 'stacks-network 10s ease-in-out infinite',
        'premium-shimmer': 'premium-shimmer 3s ease-in-out infinite',
        'cyber-wave': 'cyber-wave 4s ease-in-out infinite',
        'holographic-shift-advanced': 'holographic-shift-advanced 6s ease-in-out infinite',
        'neural-sync': 'neural-sync 3s ease-in-out infinite',
        'blockchain-verify': 'blockchain-verify 2s ease-in-out infinite',
        'cyber-aurora': 'cyber-aurora 15s ease-in-out infinite',
        'premium-glow': 'premium-glow 2s ease-in-out infinite alternate',
        'cyber-pulse': 'cyber-pulse 1.5s ease-in-out infinite',
        'holographic-float': 'holographic-float 8s ease-in-out infinite',
        'neural-network': 'neural-network 12s ease-in-out infinite',
        'cyber-energy': 'cyber-energy 3s ease-in-out infinite',
        'blockchain-flow': 'blockchain-flow 5s ease-in-out infinite',
        'premium-shine': 'premium-shine 4s ease-in-out infinite',
        'cyber-grid-pulse': 'cyber-grid-pulse 6s ease-in-out infinite',
        'holographic-scan': 'holographic-scan 3s linear infinite',
        'neural-ripple': 'neural-ripple 2s ease-in-out infinite',
        'cyber-connection': 'cyber-connection 4s ease-in-out infinite',
        'blockchain-verify-success': 'blockchain-verify-success 1s ease-out',
        'premium-float': 'premium-float 6s ease-in-out infinite',
        'cyber-aurora-advanced': 'cyber-aurora-advanced 20s ease-in-out infinite',
        'neural-sync-advanced': 'neural-sync-advanced 8s ease-in-out infinite',
        'holographic-energy': 'holographic-energy 5s ease-in-out infinite',
        'cyber-grid-advanced': 'cyber-grid-advanced 25s linear infinite',
        'premium-holographic': 'premium-holographic 10s ease-in-out infinite',
        'neural-network-advanced': 'neural-network-advanced 15s ease-in-out infinite',
        'cyber-pulse-advanced': 'cyber-pulse-advanced 3s ease-in-out infinite',
        'holographic-rainbow-advanced': 'holographic-rainbow-advanced 12s linear infinite',
        'blockchain-energy': 'blockchain-energy 4s ease-in-out infinite',
        'cyber-aurora-premium': 'cyber-aurora-premium 30s ease-in-out infinite',
        'neural-sync-premium': 'neural-sync-premium 10s ease-in-out infinite',
        'holographic-grid': 'holographic-grid 18s linear infinite',
        'cyber-network': 'cyber-network 14s ease-in-out infinite',
        'premium-cyber': 'premium-cyber 8s ease-in-out infinite',
        'neural-aurora-premium': 'neural-aurora-premium 25s ease-in-out infinite',
        'holographic-network': 'holographic-network 16s ease-in-out infinite',
        'cyber-sync': 'cyber-sync 6s ease-in-out infinite',
        'blockchain-aurora': 'blockchain-aurora 22s ease-in-out infinite',
        'premium-neural': 'premium-neural 12s ease-in-out infinite',
        'cyber-holographic': 'cyber-holographic 9s ease-in-out infinite',
        'neural-cyber': 'neural-cyber 7s ease-in-out infinite',
        'holographic-cyber': 'holographic-cyber 11s ease-in-out infinite',
        'cyber-neural': 'cyber-neural 13s ease-in-out infinite',
        'premium-blockchain': 'premium-blockchain 17s ease-in-out infinite',
        'neural-blockchain': 'neural-blockchain 19s ease-in-out infinite',
        'holographic-blockchain': 'holographic-blockchain 21s ease-in-out infinite',
        'cyber-blockchain': 'cyber-blockchain 23s ease-in-out infinite',
        'premium-neural-cyber': 'premium-neural-cyber 24s ease-in-out infinite',
        'holographic-neural-cyber': 'holographic-neural-cyber 26s ease-in-out infinite',
        'cyber-neural-holographic': 'cyber-neural-holographic 27s ease-in-out infinite',
        'neural-cyber-holographic': 'neural-cyber-holographic 28s ease-in-out infinite',
        'blockchain-neural-cyber': 'blockchain-neural-cyber 29s ease-in-out infinite',
        'premium-holographic-neural': 'premium-holographic-neural 31s ease-in-out infinite',
        'cyber-premium-holographic': 'cyber-premium-holographic 32s ease-in-out infinite',
        'neural-premium-cyber': 'neural-premium-cyber 33s ease-in-out infinite',
        'holographic-premium-neural': 'holographic-premium-neural 34s ease-in-out infinite',
        'cyber-holographic-premium': 'cyber-holographic-premium 35s ease-in-out infinite',
        'neural-holographic-premium': 'neural-holographic-premium 36s ease-in-out infinite',
        'blockchain-cyber-premium': 'blockchain-cyber-premium 37s ease-in-out infinite',
        'premium-blockchain-cyber': 'premium-blockchain-cyber 38s ease-in-out infinite',
        'holographic-blockchain-premium': 'holographic-blockchain-premium 39s ease-in-out infinite',
        'cyber-blockchain-premium': 'cyber-blockchain-premium 40s ease-in-out infinite',
        'neural-blockchain-premium': 'neural-blockchain-premium 41s ease-in-out infinite',
        'premium-neural-blockchain': 'premium-neural-blockchain 42s ease-in-out infinite',
        'holographic-neural-blockchain': 'holographic-neural-blockchain 43s ease-in-out infinite',
        'cyber-neural-blockchain': 'cyber-neural-blockchain 44s ease-in-out infinite',
        'neural-cyber-blockchain': 'neural-cyber-blockchain 45s ease-in-out infinite',
        'blockchain-neural-cyber-premium': 'blockchain-neural-cyber-premium 46s ease-in-out infinite',
        'premium-blockchain-neural-cyber': 'premium-blockchain-neural-cyber 47s ease-in-out infinite',
        'holographic-premium-blockchain-neural': 'holographic-premium-blockchain-neural 48s ease-in-out infinite',
        'cyber-premium-blockchain-neural': 'cyber-premium-blockchain-neural 49s ease-in-out infinite',
        'neural-premium-blockchain-cyber': 'neural-premium-blockchain-cyber 50s ease-in-out infinite',
        'holographic-cyber-premium-blockchain': 'holographic-cyber-premium-blockchain 51s ease-in-out infinite',
        'cyber-holographic-premium-blockchain': 'cyber-holographic-premium-blockchain 52s ease-in-out infinite',
        'neural-holographic-cyber-premium': 'neural-holographic-cyber-premium 53s ease-in-out infinite',
        'blockchain-holographic-cyber-premium': 'blockchain-holographic-cyber-premium 54s ease-in-out infinite',
        'premium-holographic-cyber-blockchain': 'premium-holographic-cyber-blockchain 55s ease-in-out infinite',
        'cyber-blockchain-holographic-premium': 'cyber-blockchain-holographic-premium 56s ease-in-out infinite',
        'neural-cyber-holographic-blockchain': 'neural-cyber-holographic-blockchain 57s ease-in-out infinite',
        'holographic-neural-cyber-blockchain': 'holographic-neural-cyber-blockchain 58s ease-in-out infinite',
        'blockchain-neural-holographic-cyber': 'blockchain-neural-holographic-cyber 59s ease-in-out infinite',
        'premium-cyber-neural-holographic': 'premium-cyber-neural-holographic 60s ease-in-out infinite',
      },
      keyframes: {
        'neural-pulse': {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.8' },
        },
        'neural-drift': {
          '0%': { transform: 'translateX(0) translateY(0)' },
          '25%': { transform: 'translateX(10px) translateY(-5px)' },
          '50%': { transform: 'translateX(-5px) translateY(10px)' },
          '75%': { transform: 'translateX(-10px) translateY(-5px)' },
          '100%': { transform: 'translateX(0) translateY(0)' },
        },
        'neural-aurora': {
          '0%, 100%': { 
            backgroundPosition: '0% 0%, 100% 100%, 50% 50%',
            opacity: '0.3'
          },
          '50%': { 
            backgroundPosition: '100% 100%, 0% 0%, 25% 75%',
            opacity: '0.6'
          },
        },
        'neon-flicker': {
          '0%, 100%': { opacity: '1' },
          '25%': { opacity: '0.8' },
          '50%': { opacity: '0.9' },
          '75%': { opacity: '0.7' },
        },
        'neon-pulse': {
          '0%, 100%': { 
            boxShadow: '0 0 10px rgba(85, 70, 255, 0.6), 0 0 20px rgba(85, 70, 255, 0.5), 0 0 40px rgba(85, 70, 255, 0.4)'
          },
          '50%': { 
            boxShadow: '0 0 15px rgba(85, 70, 255, 0.8), 0 0 30px rgba(85, 70, 255, 0.7), 0 0 60px rgba(85, 70, 255, 0.6)'
          },
        },
        'bitcoin-pulse': {
          '0%, 100%': { 
            boxShadow: '0 0 10px rgba(249, 115, 22, 0.6), 0 0 20px rgba(249, 115, 22, 0.5), 0 0 40px rgba(249, 115, 22, 0.4)'
          },
          '50%': { 
            boxShadow: '0 0 15px rgba(249, 115, 22, 0.8), 0 0 30px rgba(249, 115, 22, 0.7), 0 0 60px rgba(249, 115, 22, 0.6)'
          },
        },
        'stacks-pulse': {
          '0%, 100%': { 
            boxShadow: '0 0 10px rgba(85, 70, 255, 0.6), 0 0 20px rgba(85, 70, 255, 0.5), 0 0 40px rgba(85, 70, 255, 0.4)'
          },
          '50%': { 
            boxShadow: '0 0 15px rgba(85, 70, 255, 0.8), 0 0 30px rgba(85, 70, 255, 0.7), 0 0 60px rgba(85, 70, 255, 0.6)'
          },
        },
        'holographic-shift': {
          '0%': { backgroundPosition: '0% 0%' },
          '50%': { backgroundPosition: '100% 100%' },
          '100%': { backgroundPosition: '0% 0%' },
        },
        'particles-float': {
          '0%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-10px) translateX(5px)' },
          '50%': { transform: 'translateY(-20px) translateX(-5px)' },
          '75%': { transform: 'translateY(-10px) translateX(10px)' },
          '100%': { transform: 'translateY(0) translateX(0)' },
        },
        'gradient-shift': {
          '0%': { backgroundPosition: '0% 0%' },
          '50%': { backgroundPosition: '100% 100%' },
          '100%': { backgroundPosition: '0% 0%' },
        },
        'bitcoin-gradient': {
          '0%': { backgroundPosition: '0% 0%' },
          '50%': { backgroundPosition: '100% 100%' },
          '100%': { backgroundPosition: '0% 0%' },
        },
        'stacks-gradient': {
          '0%': { backgroundPosition: '0% 0%' },
          '50%': { backgroundPosition: '100% 100%' },
          '100%': { backgroundPosition: '0% 0%' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '25%': { transform: 'translateY(-10px) rotate(1deg)' },
          '50%': { transform: 'translateY(-20px) rotate(0deg)' },
          '75%': { transform: 'translateY(-10px) rotate(-1deg)' },
        },
        'glow': {
          '0%': { 
            boxShadow: '0 0 5px rgba(85, 70, 255, 0.5), 0 0 10px rgba(85, 70, 255, 0.3), 0 0 20px rgba(85, 70, 255, 0.2)'
          },
          '100%': { 
            boxShadow: '0 0 10px rgba(85, 70, 255, 0.8), 0 0 20px rgba(85, 70, 255, 0.6), 0 0 40px rgba(85, 70, 255, 0.4)'
          },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}

export default config
